# Import des data et exploration 

Ce script python à pour objectif de donner une prmière apporche de l'utilisation des libraires (cf fichier Librairies.ipynb) notamment à travers l'import du dataset ainsi que les premières exploration statistique de l'échantillon en python.

In [1]:
import numpy as np
import pandas as pd
import matplotlib as mp 

## Data brut 

Les données au format brut sont situées dans le dossier **/data** à la racine de ce notebook. 

In [4]:
#Importer les donnée à partir d'un fichier CSV 
df = pd.read_csv('../data/listing_rating_timeseries.csv', sep=";")

In [7]:
df

listing_id  star_rating  reviews_count                         day
0       23700276          4.5             14  2018-09-27 08:03:53.265088
1       23700276          4.5             14  2018-09-26 21:17:25.073404
2       18824088          4.5             69  2018-09-27 08:03:53.265088
3       18824088          4.5             69  2018-09-26 21:17:25.073404
4        3728394          4.5             97  2018-09-27 08:03:53.265088
...          ...          ...            ...                         ...
1424    12214909          5.0             19  2018-09-26 21:17:25.073404
1425     5662637          4.0             26  2018-09-27 08:03:53.265088
1426     5662637          4.0             26  2018-09-26 21:17:25.073404
1427    14330975          5.0              4  2018-09-27 08:03:53.265088
1428    14330975          5.0              4  2018-09-26 21:17:25.073404

[1429 rows x 4 columns]

In [20]:
#Check du type de donnée 
print(df.dtypes)

listing_id;star_rating;reviews_count;day    object
dtype: object


In [21]:
#Description rapide du dataset 
df.describe()

listing_id;star_rating;reviews_count;day
count                                      1429
unique                                     1429
top     23517478;5;3;2018-09-26 21:17:25.073404
freq                                          1

In [22]:
#Affichage d'une colone 
for x in df : 
    print(x) 


listing_id;star_rating;reviews_count;day


In [23]:
#affichage de la shape 
df.shape[1]

1

## Data Clean 
Les données nettoyées situées dans le dossier /clean à la racine de ce notebook. Pour plus de details consulter le script **raw_cleaning.py** à la racine. 

In [5]:
#charger le dataset clean
dataset = pd.read_csv("../data/listings_final.csv", sep=";")

In [6]:
print(dataset.head)

<bound method NDFrame.head of      Unnamed: 0  listing_id  \
0             0    28581061   
1             1      661961   
2             2     1261705   
3             3     1318834   
4             4     1677091   
5             5     2157481   
6             6     1140610   
7             7     5662637   
8             8     5981388   
9             9      149534   
10           10     7936602   
11           11     9468773   
12           12       56093   
13           13       57207   
14           14    14386985   
15           15    15366928   
16           16    15881321   
17           17     1896398   
18           18    17956827   
19           19      114543   
20           20    22199515   
21           21    22568676   
22           22    23179840   
23           23     2760689   
24           24    23871255   
25           25      170599   
26           26    24248060   
27           27    24488632   
28           28      164255   
29           29      167998   
..       

In [31]:
#définition de la variable de travail 
X = np.asarray(dataset.loc[:, ["person_capacity", "beds", "bedrooms", "bathrooms"]].values, dtype="float")
print(X)

[[ 1.   1.   1.   2. ]
 [ 2.   1.   1.   1. ]
 [ 1.   1.   1.   1. ]
 ..., 
 [ 4.   2.   1.   1. ]
 [ 6.   4.   2.   1.5]
 [ 2.   1.   1.   1. ]]


In [27]:
#calcul de la moyenne 
means = sum(X) / X.shape[0]
#calcul de la variance 
variance = sum((X - means)**2) / X.shape[0]
std = np.sqrt(variance)

In [28]:
#calcul de la covariance 
covar = np.zeros((X.shape[1], X.shape[1]))  # Matrice de covariance
#calcul de la corrélation 
corr = np.zeros((X.shape[1], X.shape[1]))  # Matrice de corrélation

#affichage de la variance 
print(variance)

[ 4.791776    2.250864    0.995724    0.27461975]


## Construction des matrices 

In [32]:
for i in range(X.shape[1]):
	for j in range(i+1):
		covar[i, j] = covar[j, i] = np.dot(X[:,i], X[:,j]) / X.shape[0] - means[i] * means[j]
		corr[i, j] = corr[j, i] = covar[i, j] / (std[i] * std[j])
	

print(means)
print("Matrice des covariances :")
print(covar)
print("Matrice des corrélations :")
print(corr)

[ 3.668   2.056   1.326   1.2305]
Matrice des covariances :
[[ 4.791776    2.284592    1.587232    0.663026  ]
 [ 2.284592    2.250864    1.026744    0.429092  ]
 [ 1.587232    1.026744    0.995724    0.347357  ]
 [ 0.663026    0.429092    0.347357    0.27461975]]
Matrice des corrélations :
[[ 1.          0.69564196  0.72664564  0.57798481]
 [ 0.69564196  1.          0.6858325   0.54577031]
 [ 0.72664564  0.6858325   1.          0.66426395]
 [ 0.57798481  0.54577031  0.66426395  1.        ]]
